sweetness, cream, pure vanilla

diff --git a/jffs/scripts/wan/changewan b/jffs/scripts/wan/changewan
--- a/jffs/scripts/wan/changewan
+++ b/jffs/scripts/wan/changewan
@@ -19,88 +19,88 @@ CHANGEWANPID=$PIDDIR/changewan.pid
 
 wanlogger $LOG_DEBUG "$BN: starting"
 
-getstatus () {
+getstatus() {
   if [ $# -ne 1 ]; then
     echo "Usage: getstatus <WAN>"
     wanlogger $LOG_ERR "Usage: getstatus <WAN>"
     return 0
   fi
 
-  WANSTATUS=`cat $TMPDIR/$STATROOT.$1 | cut -f1 -d' '`
+  WANSTATUS=$(cat $TMPDIR/$STATROOT.$1 | cut -f1 -d' ')
 
   wanlogger $LOG_DEBUG "$BN: getstatus $1 $WANSTATUS"
 
   case $WANSTATUS in
-    "up")
-      return 3
-      ;;
-    "recovering")
-      return 2
-      ;;
-    "link")
-      return 1
-      ;;
-    "down")
-      return 0
-      ;;
-    *)
-      wanlogger $LOG_ERR "getstatus: unknown status $WANSTATUS for $1"
-      return 0
-      ;;
+  "up")
+    return 3
+    ;;
+  "recovering")
+    return 2
+    ;;
+  "link")
+    return 1
+    ;;
+  "down")
+    return 0
+    ;;
+  *)
+    wanlogger $LOG_ERR "getstatus: unknown status $WANSTATUS for $1"
+    return 0
+    ;;
   esac
 }
 
 # check that no other changewan is running
 I=0
-ST=$((5+$$%10))    # randomize sleep time with PID
+ST=$((5 + $$ % 10)) # randomize sleep time with PID
 while [ -f $CHANGEWANPID ] && [ $I -lt 4 ]; do
   wanlogger $LOG_WARNING "$BN: another $BN is running, pass $I, sleeping $ST"
   sleep $ST
-  I=$(($I+1))
+  I=$(($I + 1))
 done
 
-echo $$ > $CHANGEWANPID
+echo $$ >$CHANGEWANPID
 
 if [ $# -eq 1 ] && [ "$1" = "force" ]; then
-  ROUTESTAT="force"    # force configroutes to run
+  ROUTESTAT="force" # force configroutes to run
 else
-  ROUTESTAT=`cat $ROUTESTATFILE | cut -f1 -d' '`
+  ROUTESTAT=$(cat $ROUTESTATFILE | cut -f1 -d' ')
 fi
 
 I=0
 WANSTAT=0
 
-for WAN in $WANLIST; do   # assemble WANSTAT for each link
+for WAN in $WANLIST; do # assemble WANSTAT for each link
   getstatus $WAN
-  WANSTAT=$(($WANSTAT+($?<<$I)))
+  WANSTAT=$(($WANSTAT + ($? << $I)))
 
   wanlogger $LOG_DEBUG "$BN: $WAN $I $WANSTAT"
-  I=$(($I+2))
+  I=$(($I + 2))
 done
 
 wanlogger $LOG_DEBUG "$BN: WANSTAT $WANSTAT"
 
-if [ -f $FORCEROUTE ]; then  # a route is being forced
-  NEWSTAT=`cat $FORCEROUTE | cut -f1 -d' '`
-  wanlogger $LOG_INFO "$BN: route forced to $NEWSTAT at `date '+%d%b%g %H%M%S'`"
+if [ -f $FORCEROUTE ]; then # a route is being forced
+  NEWSTAT=$(cat $FORCEROUTE | cut -f1 -d' ')
+  wanlogger $LOG_INFO "$BN: route forced to $NEWSTAT at $(date '+%d%b%g %H%M%S')"
 else
   case $WANSTAT in
-     11|7|6|3|2)
-       NEWSTAT=wan1
-       ;;
-     14|13|12|9|8)
-       NEWSTAT=wan2
-       ;;
-     15|10)
-       NEWSTAT=default
-       ;;
-     5|4|1|0)
-       NEWSTAT=down
-       ;;
-     *)                         # invalid state
-       wanlogger $LOG_ERR "$BN: invalid WANSTAT $WANSTAT"
-       exit 1
-       ;;
+  11 | 7 | 6 | 3 | 2)
+    NEWSTAT=wan1
+    ;;
+  14 | 13 | 12 | 9 | 8)
+    NEWSTAT=wan2
+    ;;
+  15 | 10)
+    NEWSTAT=default
+    ;;
+  5 | 4 | 1 | 0)
+    NEWSTAT=down
+    ;;
+  *) # invalid state
+    wanlogger $LOG_ERR "$BN: invalid WANSTAT $WANSTAT"
+    exit 1
+    ;;
   esac
 fi
 
@@ -108,8 +108,8 @@ wanlogger $LOG_DEBUG "$BN: NEWSTAT $NEWSTAT ROUTESTAT $ROUTESTAT"
 
 if [ "$NEWSTAT" != "$ROUTESTAT" ]; then
   $CONFIGROUTES $NEWSTAT
-  wanlogger $LOG_INFO "$BN: Route changed from $ROUTESTAT to $NEWSTAT at `date '+%d%b%g %H%M%S'`"
-  $SENDSTATUS $BN "Route changed from $ROUTESTAT to $NEWSTAT at `date '+%d%b%g %H%M%S'`" 2>/dev/null >&2 &
+  wanlogger $LOG_INFO "$BN: Route changed from $ROUTESTAT to $NEWSTAT at $(date '+%d%b%g %H%M%S')"
+  $SENDSTATUS $BN "Route changed from $ROUTESTAT to $NEWSTAT at $(date '+%d%b%g %H%M%S')" 2>/dev/null >&2 &
 fi
 
 wanlogger $LOG_DEBUG "$BN: complete"
@@ -117,4 +117,3 @@ wanlogger $LOG_DEBUG "$BN: complete"
 rm $CHANGEWANPID
 
 exit 0
-
diff --git a/jffs/scripts/wan/clockupdate b/jffs/scripts/wan/clockupdate
--- a/jffs/scripts/wan/clockupdate
+++ b/jffs/scripts/wan/clockupdate
@@ -10,11 +10,11 @@
 
 wanlogger $LOG_DEBUG "$BN: started"
 
-NTPSERVER="`nvram get ntp_server`"
+NTPSERVER="$(nvram get ntp_server)"
 
 ntpclient $NTPSERVER
 
-if [ $? -ne 0 ]; then   # update failed
+if [ $? -ne 0 ]; then # update failed
   wanlogger $LOG_WARNING "$BN: ntpclient failed for $NTPSERVER #10 $BN"
   exit 1
 fi
diff --git a/jffs/scripts/wan/linkd b/jffs/scripts/wan/linkd
--- a/jffs/scripts/wan/linkd
+++ b/jffs/scripts/wan/linkd
@@ -19,25 +19,25 @@ if [ $# -ne 1 ]; then
   exit 1
 fi
 
-WANNAME=$1                              # wan interface name
-STATFILE=$TMPDIR/$STATROOT.$WANNAME     # status file
-HBFILE=$TMPDIR/$HBROOT.$WANNAME         # heartbeat file
-PIDFILE=$PIDDIR/linkd${WANNAME}.pid     # PID file
+WANNAME=$1                          # wan interface name
+STATFILE=$TMPDIR/$STATROOT.$WANNAME # status file
+HBFILE=$TMPDIR/$HBROOT.$WANNAME     # heartbeat file
+PIDFILE=$PIDDIR/linkd${WANNAME}.pid # PID file
 
-readiface () {
+readiface() {
   . /jffs/scripts/wan/global
 
-  WANCFG=`eval echo $"CONFIG${WANNAME}"`       # read linkd configuration
-  PINGRATE=`echo $WANCFG | cut -f2 -d' '`      # time delay between pings (sec)
-  PINGCOUNT=`echo $WANCFG | cut -f3 -d' '`     # number of pings for each check
-  PINGSIZE=`echo $WANCFG | cut -f4 -d' '`      # size of ICMP packets in bytes
-  FAILCOUNT=`echo $WANCFG | cut -f5 -d' '`     # number of failures to down
-  RESTOREDELAY=`echo $WANCFG | cut -f6 -d' '`  # failback delay time (sec)
+  WANCFG=$(eval echo $"CONFIG${WANNAME}")      # read linkd configuration
+  PINGRATE=$(echo $WANCFG | cut -f2 -d' ')     # time delay between pings (sec)
+  PINGCOUNT=$(echo $WANCFG | cut -f3 -d' ')    # number of pings for each check
+  PINGSIZE=$(echo $WANCFG | cut -f4 -d' ')     # size of ICMP packets in bytes
+  FAILCOUNT=$(echo $WANCFG | cut -f5 -d' ')    # number of failures to down
+  RESTOREDELAY=$(echo $WANCFG | cut -f6 -d' ') # failback delay time (sec)
   WANIF=$(nvram get ${WANNAME}_ifname)         # WAN target interface
-  ROUTEIPCNT=`echo $DNSLIST | wc -w`          # count of route IP addresses
-  wanlogger $LOG_INFO  "$BN: $WANNAME configuration $PINGRATE $PINGCOUNT $PINGSIZE $FAILCOUNT $RESTOREDELAY #09 linkd"
-  WANIP=$(nvram get ${WANNAME}_ping)           # WAN target IP address
-  if [ -z $WANIP ]; then                       # Check ping IP override
+  ROUTEIPCNT=$(echo $DNSLIST | wc -w)          # count of route IP addresses
+  wanlogger $LOG_INFO "$BN: $WANNAME configuration $PINGRATE $PINGCOUNT $PINGSIZE $FAILCOUNT $RESTOREDELAY #09 linkd"
+  WANIP=$(nvram get ${WANNAME}_ping) # WAN target IP address
+  if [ -z $WANIP ]; then             # Check ping IP override
     WANIP=$(nvram get ${WANNAME}_gateway)
   fi
 }
@@ -57,7 +57,7 @@ trap '      # re-read interface configuration
 
 wanlogger $LOG_DEBUG "$BN: start $$ $WANNAME"
 
-readiface   # read interface configuration
+readiface # read interface configuration
 
 if [ -z "$WANIP" ]; then
   echo "$BN: WAN IP not found for $WANNAME"
@@ -65,253 +65,253 @@ if [ -z "$WANIP" ]; then
   exit 2
 fi
 
-kill -0 `cat $PIDFILE` >/dev/null
+kill -0 $(cat $PIDFILE) >/dev/null
 if [ $? -eq 0 ]; then
   echo "$BN: linkd already running for $WANNAME"
   wanlogger $LOG_WARNING "$BN: linkd already running for $WANNAME"
   exit 3
 fi
 
-echo $$ > $PIDFILE
+echo $$ >$PIDFILE
 
 FAILCHK=0                       # count of link ping failures
 RFAILCHK=0                      # count of route ping failures
 FAIL1=0                         # last failure time in seconds
 FAIL2=0                         # readable last failure time
-STATE1=`date '+%s'`             # state time in seconds
-STATE2=`date '+%d%b%g %H%M%S'`  # readable state time
+STATE1=$(date '+%s')            # state time in seconds
+STATE2=$(date '+%d%b%g %H%M%S') # readable state time
 
-if [ -f $STATFILE ]; then              # read existing status file
-  WANSTAT=`cat $STATFILE | cut -f1 -d' '`
-  FAIL2=`cat $STATFILE | cut -f7- -d' '`
+if [ -f $STATFILE ]; then # read existing status file
+  WANSTAT=$(cat $STATFILE | cut -f1 -d' ')
+  FAIL2=$(cat $STATFILE | cut -f7- -d' ')
   wanlogger $LOG_DEBUG "$BN: read $WANNAME WANSTAT $WANSTAT"
-  if [ $WANSTAT = "down" ]; then       # link down, set FAILCHK
+  if [ $WANSTAT = "down" ]; then # link down, set FAILCHK
     FAILCHK=$FAILCOUNT
-  elif [ $WANSTAT = "link" ]; then    # route down, set RFAILCHK
+  elif [ $WANSTAT = "link" ]; then # route down, set RFAILCHK
     RFAILCHK=$FAILCOUNT
-  elif [ $WANSTAT != "up" ] && [ $WANSTAT != "recovering" ]; then      # invalid status
+  elif [ $WANSTAT != "up" ] && [ $WANSTAT != "recovering" ]; then # invalid status
     unset WANSTAT
   fi
 fi
 
 wanlogger $LOG_DEBUG "$BN: starting $WANNAME, WANSTAT $WANSTAT"
 
-if [ -z $WANSTAT ]; then   # no existing WANSTAT, initialize
+if [ -z $WANSTAT ]; then # no existing WANSTAT, initialize
   wanlogger $LOG_DEBUG "$BN: initialize $WANNAME WANSTAT"
   WANSTAT="up"
-  echo "$WANSTAT $STATE1 $STATE2 init" > $STATFILE
+  echo "$WANSTAT $STATE1 $STATE2 init" >$STATFILE
 fi
 
-$CHANGEWAN &                     # check wan configuration
+$CHANGEWAN & # check wan configuration
 
 while true; do
-  date '+%s %d%b%g %H%M%S' > $HBFILE  # heartbeat for process monitor
+  date '+%s %d%b%g %H%M%S' >$HBFILE # heartbeat for process monitor
 
-  PCNT=`ping -c $PINGCOUNT -W $PINGCOUNT -w $PINGCOUNT -s $PINGSIZE -I $WANIF $WANIP \
-    2>/dev/null | awk '/packets received/ {print $4}'`
+  PCNT=$(ping -c $PINGCOUNT -W $PINGCOUNT -w $PINGCOUNT -s $PINGSIZE -I $WANIF $WANIP \
+    2>/dev/null | awk '/packets received/ {print $4}')
 
   if [ -z $PCNT ]; then
     PCNT=0
   fi
 
-  if [ $PCNT -ne $PINGCOUNT ]; then  # link ping failed
-    RCNT=0                           # mark route failed, no need to check
-  else                               # link ping test succeeded, check route
-    RCNT=$PINGCOUNT                  # set RCNT in case route check is disabled
+  if [ $PCNT -ne $PINGCOUNT ]; then # link ping failed
+    RCNT=0                          # mark route failed, no need to check
+  else                              # link ping test succeeded, check route
+    RCNT=$PINGCOUNT                 # set RCNT in case route check is disabled
 
     for ROUTEIP in $DNSLIST; do
       ip route add $ROUTEIP via $WANIP dev $WANIF
       sleep 1
-      RCNT=`ping -c $PINGCOUNT -W $PINGCOUNT -w $PINGCOUNT -I $WANIF $ROUTEIP 2>/dev/null | awk '/packets received/ {print $4}'`
+      RCNT=$(ping -c $PINGCOUNT -W $PINGCOUNT -w $PINGCOUNT -I $WANIF $ROUTEIP 2>/dev/null | awk '/packets received/ {print $4}')
       ip route del $ROUTEIP via $WANIP dev $WANIF
       sleep 1
 
       if [ $RCNT -eq $PINGCOUNT ]; then
-        break;
+        break
       else
-        wanlogger $LOG_DEBUG "$BN: $WANNAME $ROUTEIP route ping fail $RCNT #02 $WANNAME $(($PINGCOUNT-$RCNT)) 1"
+        wanlogger $LOG_DEBUG "$BN: $WANNAME $ROUTEIP route ping fail $RCNT #02 $WANNAME $(($PINGCOUNT - $RCNT)) 1"
       fi
     done
   fi
 
   PINGRATEADJ=0
 
-  if [ $PCNT -ne $PINGCOUNT ] || \
+  if [ $PCNT -ne $PINGCOUNT ] ||
     [ $RCNT -ne $PINGCOUNT ]; then # ping test failed
 
-    FAIL1=`date '+%s'`
-    FAIL2=`date '+%d%b%g %H%M%S'`
+    FAIL1=$(date '+%s')
+    FAIL2=$(date '+%d%b%g %H%M%S')
 
     if [ $PCNT -ne $PINGCOUNT ]; then
       PINGRATEADJ=1
       if [ $FAILCHK -lt $FAILCOUNT ]; then
-        FAILCHK=$(($FAILCHK+1))
+        FAILCHK=$(($FAILCHK + 1))
       fi
     fi
 
     if [ $RCNT -ne $PINGCOUNT ]; then
-      PINGRATEADJ=$(($PINGRATEADJ+$ROUTEIPCNT))
+      PINGRATEADJ=$(($PINGRATEADJ + $ROUTEIPCNT))
       if [ $RFAILCHK -lt $FAILCOUNT ]; then
-        RFAILCHK=$(($RFAILCHK+1))
+        RFAILCHK=$(($RFAILCHK + 1))
       fi
     fi
   fi
 
-  if [ $PCNT -ne $PINGCOUNT ]; then  # link ping failure
+  if [ $PCNT -ne $PINGCOUNT ]; then # link ping failure
     case $WANSTAT in
-      "up")
-        if [ $FAILCHK -eq $FAILCOUNT ]; then  # WAN link declared dead
-          WANSTAT="down"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_WARNING "$BN: $WANNAME $WANSTAT #03 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-          $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
-        else
-          wanlogger $LOG_INFO \
-          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #01 $WANNAME $(($PINGCOUNT-$PCNT)) $FAILCHK"
-        fi
-        ;;
-      "recovering"|"link")
-        if [ $FAILCHK -eq $FAILCOUNT ]; then  # WAN link declared dead
-          WANSTAT="down"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #03 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        else
-          wanlogger $LOG_DEBUG \
-          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $wANNAME $(($PINGCOUNT-$RCNT)) $RFAILCHK"
-        fi
-        ;;
-      "down")  # no action required
-        ;;
-      *)
-        wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
-        rm -f $PIDFILE
-        exit 5
-        ;;
+    "up")
+      if [ $FAILCHK -eq $FAILCOUNT ]; then # WAN link declared dead
+        WANSTAT="down"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_WARNING "$BN: $WANNAME $WANSTAT #03 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+        $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
+      else
+        wanlogger $LOG_INFO \
+          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #01 $WANNAME $(($PINGCOUNT - $PCNT)) $FAILCHK"
+      fi
+      ;;
+    "recovering" | "link")
+      if [ $FAILCHK -eq $FAILCOUNT ]; then # WAN link declared dead
+        WANSTAT="down"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #03 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      else
+        wanlogger $LOG_DEBUG \
+          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $wANNAME $(($PINGCOUNT - $RCNT)) $RFAILCHK"
+      fi
+      ;;
+    "down") # no action required
+      ;;
+    *)
+      wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
+      rm -f $PIDFILE
+      exit 5
+      ;;
     esac
-  elif  [ $RCNT -ne $PINGCOUNT ]; then     # route ping failed
+  elif [ $RCNT -ne $PINGCOUNT ]; then # route ping failed
     if [ $PCNT -eq $PINGCOUNT ] && [ $FAILCHK -gt 0 ]; then
-      FAILCHK=$(($FAILCHK-1))
+      FAILCHK=$(($FAILCHK - 1))
     fi
 
     case $WANSTAT in
-      "up")
-        if [ $RFAILCHK -eq $FAILCOUNT ]; then  # WAN route declared dead
-          WANSTAT="link"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_WARNING "$BN: $WANNAME $WANSTAT #04 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-          $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
-        else
-          wanlogger $LOG_INFO \
-          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $WANNAME $((PINGCOUNT-$RCNT)) $RFAILCHK"
-        fi
-        ;;
-      "recovering")
-        if [ $RFAILCHK -eq $FAILCOUNT ]; then  # WAN route declared dead
-          WANSTAT="link"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        else
-          wanlogger $LOG_DEBUG \
-          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $(($PINGCOUNT-$RCNT)) $RFAILCHK"
-        fi
-        ;;
-      "link")  # no action required
-        ;;
-      "down")
-        if [ $FAILCHK -eq 0 ]; then  # link online
-          WANSTAT="link"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        else
-          wanlogger $LOG_DEBUG \
-          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $WANNAME $(($PINGCOUNT-$RCNT)) $RFAILCHK"
-        fi
-        ;;
-      *)
-        wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
-        rm -f $PIDFILE
-        exit 5
-        ;;
+    "up")
+      if [ $RFAILCHK -eq $FAILCOUNT ]; then # WAN route declared dead
+        WANSTAT="link"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_WARNING "$BN: $WANNAME $WANSTAT #04 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+        $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
+      else
+        wanlogger $LOG_INFO \
+          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $WANNAME $((PINGCOUNT - $RCNT)) $RFAILCHK"
+      fi
+      ;;
+    "recovering")
+      if [ $RFAILCHK -eq $FAILCOUNT ]; then # WAN route declared dead
+        WANSTAT="link"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      else
+        wanlogger $LOG_DEBUG \
+          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $(($PINGCOUNT - $RCNT)) $RFAILCHK"
+      fi
+      ;;
+    "link") # no action required
+      ;;
+    "down")
+      if [ $FAILCHK -eq 0 ]; then # link online
+        WANSTAT="link"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      else
+        wanlogger $LOG_DEBUG \
+          "$BN: ping fail $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK #02 $WANNAME $(($PINGCOUNT - $RCNT)) $RFAILCHK"
+      fi
+      ;;
+    *)
+      wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
+      rm -f $PIDFILE
+      exit 5
+      ;;
     esac
-  else                   # ping test succeeded
+  else # ping test succeeded
     if [ $PCNT -eq $PINGCOUNT ] && [ $FAILCHK -gt 0 ]; then
-      FAILCHK=$(($FAILCHK-1))
+      FAILCHK=$(($FAILCHK - 1))
     fi
 
     if [ $RCNT -eq $PINGCOUNT ] && [ $RFAILCHK -gt 0 ]; then
-      RFAILCHK=$(($RFAILCHK-1))
+      RFAILCHK=$(($RFAILCHK - 1))
     fi
 
     case $WANSTAT in
-      "up")  # no action required
-        ;;
-      "recovering")
-        if [ `date '+%s'` -gt $(($STATE1+$RESTOREDELAY)) ]; then # change to up
-          WANSTAT="up"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_NOTICE "$BN: $WANNAME $WANSTAT #06 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-          $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
-        else
-          wanlogger $LOG_DEBUG \
+    "up") # no action required
+      ;;
+    "recovering")
+      if [ $(date '+%s') -gt $(($STATE1 + $RESTOREDELAY)) ]; then # change to up
+        WANSTAT="up"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_NOTICE "$BN: $WANNAME $WANSTAT #06 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+        $SENDSTATUS "$WANNAME $WANSTAT" "$WANNAME $WANSTAT at $STATE2" &
+      else
+        wanlogger $LOG_DEBUG \
           "$BN: ping succeed $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK"
-        fi
-        ;;
-      "link")
-        if [ $FAILCHK -eq 0 ] && [ $RFAILCHK -eq 0 ]; then  # route recovering
-          WANSTAT="recovering"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #05 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        else
-          wanlogger $LOG_DEBUG \
+      fi
+      ;;
+    "link")
+      if [ $FAILCHK -eq 0 ] && [ $RFAILCHK -eq 0 ]; then # route recovering
+        WANSTAT="recovering"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #05 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      else
+        wanlogger $LOG_DEBUG \
           "$BN: ping succeed $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK"
-        fi
-        ;;
-      "down")
-        if [ $FAILCHK -eq 0 ] && [ $RFAILCHK -eq 0 ]; then  # route recovering
-          WANSTAT="recovering"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #05 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        elif [ $FAILCHK -eq 0 ]; then  # WAN link up
-          WANSTAT="link"
-          STATE1=`date '+%s'`
-          STATE2=`date '+%d%b%g %H%M%S'`
-          wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
-          echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" > $STATFILE
-          $CHANGEWAN &
-        else
-          wanlogger $LOG_DEBUG \
+      fi
+      ;;
+    "down")
+      if [ $FAILCHK -eq 0 ] && [ $RFAILCHK -eq 0 ]; then # route recovering
+        WANSTAT="recovering"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #05 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      elif [ $FAILCHK -eq 0 ]; then # WAN link up
+        WANSTAT="link"
+        STATE1=$(date '+%s')
+        STATE2=$(date '+%d%b%g %H%M%S')
+        wanlogger $LOG_INFO "$BN: $WANNAME $WANSTAT #04 $WANNAME "
+        echo "$WANSTAT $STATE1 $STATE2 last failure $FAIL2" >$STATFILE
+        $CHANGEWAN &
+      else
+        wanlogger $LOG_DEBUG \
           "$BN: ping succeed $WANNAME $PCNT of $PINGCOUNT, $FAILCHK route $RCNT of $PINGCOUNT, $RFAILCHK"
-        fi
-        ;;
-      *)
-        wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
-        rm -f $PIDFILE
-        exit 5
-        ;;
+      fi
+      ;;
+    *)
+      wanlogger $LOG_ERR "$BN: Unknown $WANNAME WANSTAT $WANSTAT"
+      rm -f $PIDFILE
+      exit 5
+      ;;
     esac
   fi
 
@@ -322,4 +322,3 @@ rm -f $PIDFILE
 
 wanlogger $LOG_ERR "$BN: abnormal exit"
 exit 6
-
diff --git a/jffs/scripts/wan/monitord b/jffs/scripts/wan/monitord
--- a/jffs/scripts/wan/monitord
+++ b/jffs/scripts/wan/monitord
@@ -16,9 +16,9 @@
 
 CRONALARM=$TMPDIR/cronalarm
 
-HBFILE=$TMPDIR/$HBROOT.monitord                # heartbeat file
+HBFILE=$TMPDIR/$HBROOT.monitord # heartbeat file
 
-reload () {  # reload global configuration
+reload() { # reload global configuration
   . /jffs/scripts/wan/global
 }
 
@@ -27,24 +27,24 @@ trap '
   wanlogger $LOG_INFO "$BN: Reload configuration #08 monitord"
 ' SIGUSR2
 
-checkhb () {
+checkhb() {
   if [ $# -ne 2 ]; then
     echo "Usage: gethb <process> <fail time>"
     wanlogger $LOG_ERR "Usage: gethb <process> <fail time>"
     return 1
   fi
 
-  HBTIME=`cat $TMPDIR/$HBROOT.$1 | cut -f1 -d' '`
+  HBTIME=$(cat $TMPDIR/$HBROOT.$1 | cut -f1 -d' ')
 
   wanlogger $LOG_DEBUG "$BN: gethb $1 $2 $HBTIME"
 
-  if [ -z $HBTIME ]; then   # allow time for hb write to complete, then reread
-    sleep 1                 # See Note 1 below
-    HBTIME=`cat $TMPDIR/$HBROOT.$1 | cut -f1 -d' '`
+  if [ -z $HBTIME ]; then # allow time for hb write to complete, then reread
+    sleep 1               # See Note 1 below
+    HBTIME=$(cat $TMPDIR/$HBROOT.$1 | cut -f1 -d' ')
     wanlogger $LOG_DEBUG "$BN: gethb $1 $2 reread $HBTIME"
   fi
 
-  if [ `date +%s` -gt $(($HBTIME+$2)) ]; then
+  if [ $(date +%s) -gt $(($HBTIME + $2)) ]; then
     return 1
   else
     return 0
@@ -53,40 +53,40 @@ checkhb () {
 
 wanlogger $LOG_DEBUG "$BN: starting"
 
-PIDFILE=$PIDDIR/monitord.pid	# PID file
+PIDFILE=$PIDDIR/monitord.pid # PID file
 
-kill -0 `cat $PIDFILE` >/dev/null
+kill -0 $(cat $PIDFILE) >/dev/null
 if [ $? -eq 0 ]; then
   wanlogger $LOG_ERR "$BN: monitord already running"
   exit 1
 fi
 
-echo $$ > $PIDFILE
+echo $$ >$PIDFILE
 
-date '+%s %d%b%g %H%M%S' > $TMPDIR/$HBROOT.procmon # allow time for cron to run
+date '+%s %d%b%g %H%M%S' >$TMPDIR/$HBROOT.procmon # allow time for cron to run
 rm $CRONALARM
 
 while true; do
-  date '+%s %d%b%g %H%M%S' > $HBFILE        # heartbeat for process monitor
+  date '+%s %d%b%g %H%M%S' >$HBFILE # heartbeat for process monitor
 
-  sleep $CHECKRATE    # delay between status checks
+  sleep $CHECKRATE # delay between status checks
 
   # check udhcpc daemons
   for WAN in $WANLIST; do
     UDHCPCPID=$PIDDIR/udhcpc-${WAN}.pid
 
-    kill -0 `cat $UDHCPCPID` > /dev/null
-    if [ $? -ne 0 ]; then    # launch udhcpc
+    kill -0 $(cat $UDHCPCPID) >/dev/null
+    if [ $? -ne 0 ]; then # launch udhcpc
       wanlogger $LOG_NOTICE "$BN: restarting udhcpc for $WAN #08 udhcpc"
       rm -f $UDHCPCPID
-      udhcpc -i `nvram get ${WAN}_ifname` -p $UDHCPCPID -s $WANDIR/udhcpc-${WAN} &
-      sleep 5  # allow time for udhcpc daemon start
+      udhcpc -i $(nvram get ${WAN}_ifname) -p $UDHCPCPID -s $WANDIR/udhcpc-${WAN} &
+      sleep 5 # allow time for udhcpc daemon start
     fi
   done
 
   # check linkd daemons
   for WAN in $WANLIST; do
-    HBRATE=`eval echo $"HBRATE${WAN}"`
+    HBRATE=$(eval echo $"HBRATE${WAN}")
     checkhb $WAN $HBRATE
     if [ $? -ne 0 ]; then # heartbeat fail
       LINKDPID=$PIDDIR/linkd${WAN}.pid
@@ -101,18 +101,18 @@ while true; do
 
   checkhb procmon $CRONALARMTIME
   if [ $? -ne 0 ]; then # heartbeat fail
-    wanlogger $LOG_DEBUG "$BN: `date +%s` HBTIME $HBTIME CRONALARMTIME $CRONALARMTIME"
-    if [ ! -f $CRONALARM ]; then   # cron alarm has not been issued
-      wanlogger $LOG_WARNING "$BN: heartbeat fail for procmon at `date '+%d%b%g %H%M%S'` hb `cat $TMPDIR/$HBROOT.procmon` #08 procmon"
-      $SENDSTATUS "cron error" "cron heartbeat failure at `date '+%d%b%g %H%M%S'` hb `cat $TMPDIR/$HBROOT.procmon`" &
-      stopservice $CROND   # restart cron daemon
+    wanlogger $LOG_DEBUG "$BN: $(date +%s) HBTIME $HBTIME CRONALARMTIME $CRONALARMTIME"
+    if [ ! -f $CRONALARM ]; then # cron alarm has not been issued
+      wanlogger $LOG_WARNING "$BN: heartbeat fail for procmon at $(date '+%d%b%g %H%M%S') hb $(cat $TMPDIR/$HBROOT.procmon) #08 procmon"
+      $SENDSTATUS "cron error" "cron heartbeat failure at $(date '+%d%b%g %H%M%S') hb $(cat $TMPDIR/$HBROOT.procmon)" &
+      stopservice $CROND # restart cron daemon
       startservice $CROND
-      touch $CRONALARM     # prevent multiple alarms
+      touch $CRONALARM # prevent multiple alarms
     fi
   elif [ -f $CRONALARM ]; then
-    wanlogger $LOG_WARNING "$BN: heartbeat resumed for procmon at `date '+%d%b%g %H%M%S'`"
-    $SENDSTATUS "cron resume" "cron heartbeat resumed at `date '+%d%b%g %H%M%S'`" &
-    rm $CRONALARM          # cron running again, reset alarm
+    wanlogger $LOG_WARNING "$BN: heartbeat resumed for procmon at $(date '+%d%b%g %H%M%S')"
+    $SENDSTATUS "cron resume" "cron heartbeat resumed at $(date '+%d%b%g %H%M%S')" &
+    rm $CRONALARM # cron running again, reset alarm
   fi
 done
 
diff --git a/jffs/scripts/wan/procmon b/jffs/scripts/wan/procmon
--- a/jffs/scripts/wan/procmon
+++ b/jffs/scripts/wan/procmon
@@ -9,37 +9,37 @@
 
 . /jffs/scripts/wan/global
 
-LOGLEVEL=$LOG_INFO       # overriding log level for procmon
+LOGLEVEL=$LOG_INFO # overriding log level for procmon
 FILELEVEL=$LOGLEVEL
 
 wanlogger $LOG_DEBUG "$BN: starting"
 
-date '+%s %d%b%g %H%M%S' > $TMPDIR/$HBROOT.procmon    # heartbeat for procmon
+date '+%s %d%b%g %H%M%S' >$TMPDIR/$HBROOT.procmon # heartbeat for procmon
 
 PIDFILE=$PIDDIR/monitord.pid
 
-HBFILE=$TMPDIR/$HBROOT.monitord    # heartbeat file
-HBWAIT=$(($CHECKRATE*2))           # maximum time to wait for monitor heartbeat
+HBFILE=$TMPDIR/$HBROOT.monitord # heartbeat file
+HBWAIT=$(($CHECKRATE * 2))      # maximum time to wait for monitor heartbeat
 
-HBTIME=`cat $HBFILE | cut -f1 -d' '`
+HBTIME=$(cat $HBFILE | cut -f1 -d' ')
 
-if [ -z $HBTIME ]; then   # allow time for hb write to complete, then reread
-  sleep 1                 # See Note 1 below
-  HBTIME=`cat $HBFILE | cut -f1 -d' '`
+if [ -z $HBTIME ]; then # allow time for hb write to complete, then reread
+  sleep 1               # See Note 1 below
+  HBTIME=$(cat $HBFILE | cut -f1 -d' ')
   wanlogger $LOG_DEBUG "$BN: reread $HBTIME"
 fi
 
-wanlogger $LOG_DEBUG "$BN: heartbeat file `cat $HBFILE`"
+wanlogger $LOG_DEBUG "$BN: heartbeat file $(cat $HBFILE)"
 wanlogger $LOG_DEBUG "$BN: HBWAIT $HBWAIT HBTIME $HBTIME"
-wanlogger $LOG_DEBUG "$BN: date `date '+%s'`"
+wanlogger $LOG_DEBUG "$BN: date $(date '+%s')"
 
-if [ `date '+%s'` -gt $(($HBTIME+$HBWAIT)) ]; then # heartbeat fail
+if [ $(date '+%s') -gt $(($HBTIME + $HBWAIT)) ]; then # heartbeat fail
   wanlogger $LOG_WARNING "$BN: heartbeat fail for monitord, restarting #08 monitord"
 
-  kill -0 `cat $PIDFILE` >/dev/null
-  if [ $? -eq 0 ]; then     # monitord is still in the process table
+  kill -0 $(cat $PIDFILE) >/dev/null
+  if [ $? -eq 0 ]; then # monitord is still in the process table
     wanlogger $LOG_ERR "$BN: monitord in process table, killing"
-    kill -9 `cat $PIDFILE`
+    kill -9 $(cat $PIDFILE)
     sleep 5
   fi
 
@@ -57,4 +57,3 @@ exit 0
 #         but before the new heartbeat timestamp is written.  The one second
 #         sleep allows time for the heartbeat write to complete.
 #############################################################################
-
